import { db } from './db.js'
import { upsertGovernmentService, type GovernmentServiceRecordInput } from './government-service-directory.js'

const verifiedOn = '2026-08-28'
const urSource = (url: string, pageTitle: string): GovernmentServiceRecordInput['sources'][number] => ({
  sourceType: 'UR_PORTAL', authorityName: 'البوابة الإلكترونية لجمهورية العراق (أور)', officialUrl: url, pageTitle, dateAccessed: verifiedOn, lastVerifiedDate: verifiedOn, verificationStatus: 'VERIFIED_UR_PORTAL',
})
const doc = (documentName: string, details: Record<string, unknown> = {}) => ({ documentName, requiredOrOptional: 'REQUIRED', originalRequired: false, copyRequired: false, certifiedCopyRequired: false, frontSideRequired: false, backSideRequired: false, expirationCheckRequired: false, ...details })

export const verifiedGovernmentServiceSeed: GovernmentServiceRecordInput[] = [
  {
    canonicalServiceId: 'ur-e-passport-booking', officialNameAr: 'الحجز الإلكتروني للحصول على جواز السفر الإلكتروني العراقي', shortNameAr: 'حجز الجواز الإلكتروني', citizenFriendlyName: 'احجز موعد إصدار أو تجديد الجواز',
    alternativeSearchNames: ['جواز', 'جواز سفر', 'تجديد جواز', 'بدل فاقد جواز', 'بدل تالف جواز'], description: 'حجز إلكتروني لإصدار الجواز الإلكتروني أو تجديده أو طلب بدل فاقد أو تالف، ثم مراجعة دائرة الجوازات في الموعد المحدد.',
    category: 'الأفراد والأحوال الشخصية', subcategory: 'الجوازات', beneficiaryTypes: ['Citizen', 'Guardian', 'Legal Representative'], responsibleMinistry: 'وزارة الداخلية العراقية', responsibleAuthority: 'مديرية الأحوال المدنية والجوازات والإقامة', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_IN_PERSON', existingServiceKey: 'e-passport', externalServiceUrl: 'https://epp.iq/home', requiredDocuments: [
      doc('البطاقة الوطنية', { originalRequired: true, copyRequired: true, issuingAuthority: 'وزارة الداخلية' }), doc('بطاقة دفع إلكتروني', { issuingAuthority: 'جهة دفع معتمدة' }),
      doc('وثائق ولي الأمر أو من ينوب عنه قانونياً', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'إذا كان عمر مقدم الطلب أقل من 18 سنة' }),
      doc('حكم من المحكمة', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'بدل فاقد أو تالف' }), doc('صورة عن الجواز القديم', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'بدل فاقد أو تالف' }),
    ], requiredInformation: ['المعلومات المطلوبة داخل نظام الجواز الإلكتروني وفق نموذج الجهة الرسمية'], eligibilityConditions: ['الحضور بتاريخ ووقت الحجز', 'دفع رسوم إصدار الجواز إلكترونياً باستخدام بطاقات الدفع النافذة'],
    feeDetails: [{ rule: 'رسوم إصدار الجواز', amount: null, currency: 'IQD', status: 'تحددها المديرية وتدفع في النظام الرسمي' }, { rule: 'استثناء من الحجز للعائلة الواحدة داخل العراق', amount: 100000, currency: 'IQD' }, { rule: 'غرامة تجاوز موعد الحجز ضمن المدة المنشورة', amount: 5000, currency: 'IQD' }],
    processingTime: 'يوم عمل', processingTimeStatus: 'OFFICIAL', citizenSteps: ['الانتقال إلى نظام الجواز الرسمي', 'قراءة التعليمات وإدخال المعلومات', 'تثبيت موعد الحجز', 'إدخال رمز التحقق المرسل برسالة نصية', 'الاحتفاظ بوثيقة الطلب وQR', 'مراجعة دائرة الجوازات في الموعد'],
    physicalPresenceRequired: true, physicalPresenceDetails: 'مراجعة دائرة الجوازات في التاريخ والوقت المحددين مع الوثائق الأصلية.', serviceOutput: 'وثيقة حجز تحتوي رقم الطلب وQR؛ إصدار الجواز عبر الجهة المختصة.', physicalDocumentRequired: true,
    legalBasis: [{ lawName: 'نظام جوازات السفر', lawNumber: '2', year: 2011, officialSource: 'https://www.moj.gov.iq/uploaded/4191.pdf' }], verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/50850/10042/cat', 'الحجز الإلكتروني للحصول على جواز السفر الإلكتروني العراقي')],
  },
  {
    canonicalServiceId: 'ur-national-card-app', officialNameAr: 'تطبيق البطاقة الوطنية', shortNameAr: 'حجز البطاقة الوطنية', citizenFriendlyName: 'احجز موعد البطاقة الوطنية', alternativeSearchNames: ['بطاقة وطنية', 'البطاقة الموحدة', 'تجديد البطاقة الوطنية', 'بدل ضائع بطاقة', 'واقعة حياتية'],
    description: 'تطبيق رسمي لحجز مواعيد إصدار البطاقة الوطنية لأول مرة والوقائع الحياتية، ومنها بيان الولادة والزواج والطلاق وتغيير الاسم أو اللقب والبدل الضائع أو التالف.', category: 'الأفراد والأحوال الشخصية', subcategory: 'البطاقة الوطنية', beneficiaryTypes: ['Citizen', 'Guardian'], responsibleMinistry: 'وزارة الداخلية العراقية', responsibleAuthority: 'مديرية الأحوال المدنية والجوازات والإقامة العامة', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'MOBILE_APP_THEN_IN_PERSON', existingServiceKey: 'national-id', externalServiceUrl: 'https://play.google.com/store/apps/details?id=com.nationalcard.qing&hl=ar',
    requiredDocuments: [doc('هوية الأحوال المدنية لجميع الأشخاص المطلوب إصدار البطاقة لهم', { originalRequired: true }), doc('بطاقة السكن', { originalRequired: true }), doc('بيان الولادة', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'لحديثي الولادة' })],
    requiredInformation: ['رقم الهاتف المحمول', 'الاسم الأول', 'اسم الأب', 'اسم العائلة', 'بيانات اختيار المحافظة والدائرة وعدد أفراد الأسرة وموعد المراجعة داخل التطبيق'], eligibilityConditions: ['إنشاء حساب ضمن تطبيق البطاقة الوطنية'], feeDetails: [{ rule: 'رسوم البطاقة الوطنية', amount: null, currency: 'IQD', status: 'تختلف حسب نوع الطلب وفق المصدر' }],
    processingTime: 'يحدد موعد الحجز من خلال التطبيق', processingTimeStatus: 'OFFICIAL', citizenSteps: ['تثبيت التطبيق الرسمي', 'إنشاء حساب', 'اختيار حجز موعد', 'اختيار المحافظة والدائرة وعدد أفراد الأسرة', 'اختيار اليوم والوقت المتاحين', 'الاحتفاظ بمعلومات المراجعة'], physicalPresenceRequired: true, physicalPresenceDetails: 'مراجعة الدائرة في الموعد المحجوز وفق تعليمات التطبيق.', serviceOutput: 'وثيقة أو معلومات حجز للمراجعة.', physicalDocumentRequired: true,
    verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51434/10042/cat', 'تطبيق البطاقة الوطنية')],
  },
  {
    canonicalServiceId: 'ur-first-driving-license', officialNameAr: 'إجراءات إصدار إجازة السياقة لأول مرة', shortNameAr: 'إجازة السياقة', citizenFriendlyName: 'اعرف خطوات إصدار إجازة السياقة', alternativeSearchNames: ['رخصة قيادة', 'إجازة سوق', 'تعلم سياقة', 'فحص طبي سياقة'],
    description: 'دليل رسمي لإجراءات إصدار إجازة السياقة لأول مرة، يبدأ بحجز الفحص الطبي وحجز مراجعة إحدى دوائر المرور.', category: 'الأفراد والأحوال الشخصية', subcategory: 'المرور والمركبات', beneficiaryTypes: ['Driver', 'Citizen'], responsibleMinistry: 'وزارة الداخلية العراقية', responsibleAuthority: 'مديرية المرور العامة', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'INFORMATION_ONLY', applicationChannel: 'ONLINE_APPOINTMENT_THEN_IN_PERSON', existingServiceKey: 'driving-license', requiredDocuments: [doc('البطاقة الوطنية'), doc('بطاقة السكن'), doc('وثيقة الفحص الطبي'), doc('استمارة الحجز الإلكتروني')],
    requiredInformation: [], eligibilityConditions: ['إجراء الفحص الطبي', 'حجز موعد مراجعة'], feeDetails: [{ rule: 'رسوم الإجازة', amount: null, currency: 'IQD', status: 'محددة قانوناً بحسب المصدر لكن من دون رقم منشور في الصفحة' }], processingTime: '2–3 ساعات', processingTimeStatus: 'OFFICIAL',
    citizenSteps: ['حجز الفحص الطبي', 'حجز موعد مراجعة إحدى دوائر المرور', 'مراجعة موقع المرور في الموعد مع استمارة الحجز', 'ملء الاستمارة والتثبيت والبصمة والتدقيق', 'إجراء الاختبار', 'دفع الرسوم واستلام الإجازة'], physicalPresenceRequired: true, physicalPresenceDetails: 'الفحص والمراجعة والبصمة واختبار السياقة واستلام الإجازة تتم حضورياً.', serviceOutput: 'إجازة سياقة.', physicalDocumentRequired: true,
    verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/40305/10044/cat', 'إجراءات إصدار إجازة السياقة لأول مرة')],
  },
  {
    canonicalServiceId: 'ur-dhiqar-sewerage-app', officialNameAr: 'تطبيق مديرية مجاري ذي قار', shortNameAr: 'بلاغ مجاري ذي قار', citizenFriendlyName: 'بلّغ عن مشكلة في شبكة المجاري', alternativeSearchNames: ['طفح مجاري', 'انسداد مجاري', 'مشكلة مجاري', 'مديرية مجاري ذي قار'],
    description: 'تطبيق رسمي لتقديم الشكاوى والبلاغات المرتبطة بشبكات الصرف الصحي في محافظة ذي قار وتحديد موقع المشكلة ومتابعة البلاغ.', category: 'الخدمات المحلية', subcategory: 'الماء والمجاري', beneficiaryTypes: ['Citizen', 'Resident'], responsibleAuthority: 'ديوان محافظة ذي قار', responsibleDepartment: 'مديرية مجاري ذي قار', administrativeLevel: 'LOCAL_GOVERNMENT', availableInDhiQar: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'MOBILE_APP', existingServiceKey: 'sewerage-service', externalServiceUrl: 'https://play.google.com/store/apps/details?id=com.technolanes.dhiqarseweragedirectorate', requiredDocuments: [], requiredInformation: ['بيانات البلاغ داخل التطبيق', 'الموقع الجغرافي للمشكلة'], eligibilityConditions: [], feeDetails: [{ rule: 'الخدمة', amount: 0, currency: 'IQD', status: 'لا توجد رسوم وفق المصدر' }], processingTimeStatus: 'NOT_PUBLISHED',
    citizenSteps: ['تثبيت التطبيق', 'تسجيل الدخول أو إنشاء حساب', 'اختيار إنشاء بلاغ', 'إدخال المعلومات وتحميل الوثائق عند الحاجة', 'تحديد الموقع الجغرافي', 'إرسال البلاغ ومتابعته من تبويب البلاغات'], physicalPresenceRequired: false, inspectionRequired: false, serviceOutput: 'رقم أو سجل بلاغ داخل التطبيق.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51675/11018/org', 'تطبيق مديرية مجاري ذي قار')],
  },
  {
    canonicalServiceId: 'ur-retirement-confirmation', officialNameAr: 'التقديم الإلكتروني للحصول على تأييد التقاعد', shortNameAr: 'تأييد التقاعد', citizenFriendlyName: 'استخرج تأييد صحة بيانات الراتب التقاعدي', alternativeSearchNames: ['تأييد تقاعد', 'تأييد راتب تقاعدي', 'صحة بيانات الراتب'],
    description: 'خدمة إلكترونية للحصول على تأييد صحة بيانات الراتب التقاعدي للعسكري والمدني.', category: 'الوظائف والتقاعد', subcategory: 'التقاعد', beneficiaryTypes: ['Retiree'], responsibleMinistry: 'وزارة المالية العراقية', responsibleAuthority: 'هيأة التقاعد الوطنية', responsibleDepartment: 'صندوق تقاعد موظفي الدولة', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE', externalServiceUrl: 'https://xdata.ur.gov.iq/user-auth?uri=org-service-view/169/381', requiredDocuments: [], requiredInformation: ['المعلومات المطلوبة في بوابة أور', 'اسم الجهة المراد عنونة البيان لها'], eligibilityConditions: ['إنشاء حساب في بوابة أور'], feeDetails: [{ rule: 'أجور الخدمة', amount: 10000, currency: 'IQD', status: 'تستقطع من الراتب التقاعدي وفق المصدر' }], processingTimeStatus: 'NOT_PUBLISHED', citizenSteps: ['تسجيل الدخول أو إنشاء حساب في بوابة أور', 'إدخال المعلومات وتحميل الوثائق إن طلب النظام', 'البحث عن البيان', 'إدخال اسم الجهة المراد عنونة البيان لها', 'تحميل الاستمارة التي تتضمن رقم الطلب وQR'], digitalDocumentAvailable: true, qrVerificationAvailable: true, serviceOutput: 'وثيقة تأييد مع رقم طلب وQR.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51047/10038/cat', 'التقديم الإلكتروني للحصول على تأييد التقاعد')],
  },
  {
    canonicalServiceId: 'ur-building-permit-governorates', officialNameAr: 'إجراءات الحصول على إجازات البناء للمحافظات', shortNameAr: 'إجازة بناء', citizenFriendlyName: 'اعرف متطلبات إجازة بناء أو إضافة بناء', alternativeSearchNames: ['بناء', 'رخصة بناء', 'إضافة بناء', 'إجازة بناء'],
    description: 'دليل رسمي لإجراءات إجازة بناء حديثة أو إضافة بناء ضمن المحافظات؛ يبدأ بطلب لدى البلدية ضمن الرقعة الجغرافية.', category: 'النقل والبنى التحتية والسكن', subcategory: 'البلديات والبناء', beneficiaryTypes: ['Citizen', 'Land Owner', 'Legal Representative'], responsibleMinistry: 'وزارة الإعمار والإسكان والبلديات العامة', responsibleAuthority: 'مديرية البلديات العامة', administrativeLevel: 'FEDERAL_MINISTRY', availableInDhiQar: true,
    serviceType: 'PHYSICAL_ONLY', applicationChannel: 'IN_PERSON', existingServiceKey: 'building-permit', requiredDocuments: [doc('سند ملكية محدث مع خارطة عقار', { notes: 'مدة النفاذ شهر أو ثلاثة أشهر حسب البلدية وفق المصدر' }), doc('مخططات مصدقة من مكتب هندسي مجاز أو مهندس معماري'), doc('خارطة تثبيت حدود من دائرة التسجيل العقاري'), doc('هوية الأحوال المدنية وشهادة الجنسية العراقية أو البطاقة الوطنية'), doc('بطاقة السكن')], requiredInformation: ['رقم الهاتف', 'البريد الإلكتروني', 'نوع البناء وعدد الطوابق'], eligibilityConditions: ['أن يكون مقدم الطلب عراقي الجنسية'], feeDetails: [{ rule: 'رسم للمركز', amount: 15000, currency: 'IQD' }, { rule: 'رسم للأقضية والنواحي', amount: 75000, currency: 'IQD' }, { rule: 'رسوم البناء والتبليط وإشغال الرصيف والترقيم', amount: null, currency: 'IQD', status: 'تحتسبها البلدية وفق المصدر' }], processingTime: '7–15 يوم عمل', processingTimeStatus: 'OFFICIAL', citizenSteps: ['تقديم طلب إلى البلدية ضمن الرقعة الجغرافية', 'مفاتحة الدوائر ذات العلاقة لعدم الممانعة عند الحاجة', 'تحديد موعد الكشف الموقعي', 'احتساب الرسوم', 'ملء نموذج الإجازة ومنحه رقماً', 'مصادقة مدير البلدية', 'منح إجازة البناء'], physicalPresenceRequired: true, physicalPresenceDetails: 'تقديم الطلب والمراجعة لدى البلدية.', inspectionRequired: true, inspectionDetails: 'كشف موقعي يحدده مساح البلدية.', serviceOutput: 'إجازة بناء.', physicalDocumentRequired: true, verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/50874/10029/org', 'إجراءات الحصول على اجازات البناء للمحافظات')],
  },
  {
    canonicalServiceId: 'ur-electricity-connection-under-50kw', officialNameAr: 'تقديم طلب إلكتروني لإيصال التيار الكهربائي للدور السكنية بقدرة أقل من 50 كيلو واط', shortNameAr: 'إيصال التيار الكهربائي', citizenFriendlyName: 'قدم طلب إيصال كهرباء لعقار بقدرة أقل من 50 كيلو واط', alternativeSearchNames: ['وصل كهرباء', 'اشتراك كهرباء', 'مقياس كهرباء', 'إيصال تيار'],
    description: 'طلب إلكتروني لإيصال التيار الكهربائي للعقار، مع تدقيق وكشف موقعي واستحصال رسوم وفق نوع العقار والمقياس.', category: 'الكهرباء والماء والخدمات المحلية', subcategory: 'الكهرباء', beneficiaryTypes: ['Citizen', 'Land Owner', 'Business Owner'], responsibleMinistry: 'وزارة الكهرباء العراقية', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_IN_PERSON', externalServiceUrl: 'https://eservice.ur.gov.iq/customer/applyService/10370', requiredDocuments: [doc('البطاقة الوطنية', { frontSideRequired: true, backSideRequired: true }), doc('سند العقار أو كتاب الوحدة الإدارية', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'خارج حدود الأمانة' }), doc('كتاب ضريبة العقار للمحلات أو إجازة بناء مصدقة', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'داخل حدود الأمانة' }), doc('قائمة حساب الكهرباء للعقار المجاور'), doc('قسام شرعي', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'إن وجد' })], requiredInformation: ['المعلومات المطلوبة داخل بوابة أور'], eligibilityConditions: ['إنشاء حساب في بوابة أور', 'يمكن تقديم طلب واحد فقط بالرقم الخاص إلى حين إنجاز الطلب السابق'], feeDetails: [{ rule: 'كشف لعقار سكني', amount: 10000, currency: 'IQD' }, { rule: 'كشف لعقار تجاري أو صناعي', amount: 15000, currency: 'IQD' }, { rule: 'كشف لعقار زراعي أو حكومي', amount: 25000, currency: 'IQD' }, { rule: 'مقياس طور واحد 10–60 أمبير', amount: 32000, currency: 'IQD' }, { rule: 'عملية الربط', amount: null, currency: 'IQD', status: 'متغير وتبدأ من 25,000 IQD وفق المصدر' }], processingTime: '5 أيام عمل', processingTimeStatus: 'OFFICIAL', citizenSteps: ['تسجيل الدخول إلى بوابة أور', 'إدخال المعلومات وتحميل الوثائق', 'حفظ وإرسال الطلب', 'تحميل وثيقة الطلب وQR', 'انتظار إشعار موعد الكشف', 'استحصال الرسوم في الموعد', 'ربط المقياس وفتح الحساب'], physicalPresenceRequired: true, physicalPresenceDetails: 'الكشف واستحصال الرسوم وربط المقياس وفق إشعارات الدائرة.', inspectionRequired: true, inspectionDetails: 'كشف موقعي من لجنة الكشف في مركز الصيانة.', digitalDocumentAvailable: true, qrVerificationAvailable: true, serviceOutput: 'رقم طلب وQR ثم اشتراك وفتح حساب بعد استكمال الإجراءات.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/50933/10036/cat', 'تقديم طلب إلكتروني لإيصال التيار الكهربائي للدور السكنية بقدرة اقل من 50 كيلو واط')],
  },
  {
    canonicalServiceId: 'ur-execution-file-opening', officialNameAr: 'تقديم طلب إلكتروني لفتح الأضابير التنفيذية - معزز بالدفع الإلكتروني', shortNameAr: 'فتح إضبارة تنفيذية', citizenFriendlyName: 'ابدأ فتح إضبارة تنفيذية لدى دوائر التنفيذ', alternativeSearchNames: ['تنفيذ حكم', 'فتح اضبارة تنفيذية', 'دائرة التنفيذ', 'قرار محكمة'],
    description: 'خدمة إلكترونية لفتح أضبارة تنفيذية للأحكام والمحررات التنفيذية، ومذكور ضمن المديريات المتاحة الناصرية الثانية.', category: 'العدل والقانون والتظلمات', subcategory: 'دوائر التنفيذ', beneficiaryTypes: ['Citizen', 'Legal Representative'], responsibleMinistry: 'وزارة العدل العراقية', responsibleAuthority: 'دوائر التنفيذ', administrativeLevel: 'FEDERAL_MINISTRY', availableInDhiQar: true, dhiQarOffice: 'الناصرية الثانية وفق المصدر',
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_IN_PERSON', externalServiceUrl: 'https://eservice.ur.gov.iq/customer/applyService/10648', requiredDocuments: [doc('البطاقة الوطنية أو هوية الأحوال المدنية', { frontSideRequired: true, backSideRequired: true }), doc('بطاقة السكن', { frontSideRequired: true, backSideRequired: true }), doc('قرار المحكمة'), doc('الوكالة', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'إذا كان التقديم من وكيل' })], eligibilityConditions: ['أن يكون مقدم الطلب صاحب العلاقة بالدرجة الأولى أو موكله بموجب وكالة أصلية عامة أو خاصة', 'إرفاق قرار المحكمة المختصة'], feeDetails: [{ rule: 'رسوم تسجيل', amount: 5000, currency: 'IQD' }, { rule: 'رسم طابع', amount: 1500, currency: 'IQD' }], processingTimeStatus: 'NOT_PUBLISHED', citizenSteps: ['تسجيل الدخول إلى بوابة أور', 'إدخال البيانات وتحميل الوثائق', 'حفظ وإرسال الطلب', 'تحميل وثيقة الطلب وQR', 'استلام إشعار الحضور لإكمال الطلب عند الحاجة'], physicalPresenceRequired: true, physicalPresenceDetails: 'قد يطلب حضور المواطن لاستكمال الطلب والدفع والإجراءات التنفيذية.', digitalDocumentAvailable: true, qrVerificationAvailable: true, serviceOutput: 'طلب فتح إضبارة تنفيذية ورقم طلب وQR.', legalBasis: [{ lawName: 'قانون التنفيذ', lawNumber: '45', year: 1980, article: '114', officialSource: 'https://moj.gov.iq/tashkelat.11/' }], verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51217/10039/cat', 'تقديم طلب إلكتروني لفتح الاضابير التنفيذية - معزز بالدفع الإلكتروني')],
  },
  {
    canonicalServiceId: 'ur-poverty-database-registration', officialNameAr: 'الاستمارة الإلكترونية للتسجيل في قاعدة بيانات الفقر', shortNameAr: 'التسجيل في قاعدة الفقر', citizenFriendlyName: 'سجل طلب شمول في قاعدة بيانات الفقر', alternativeSearchNames: ['رعاية اجتماعية', 'إعانة اجتماعية', 'الفقر', 'مظلتي'],
    description: 'استمارة إلكترونية للتسجيل في قاعدة بيانات الفقر وفق قانون رقم 11 لسنة 2014، مع بحث اجتماعي لاحق وتدقيق البيانات.', category: 'الوظائف والتقاعد', subcategory: 'الرعاية الاجتماعية', beneficiaryTypes: ['Citizen', 'Guardian', 'Resident'], responsibleMinistry: 'وزارة العمل والشؤون الاجتماعية', responsibleAuthority: 'هيئة الحماية الاجتماعية', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_FIELD_VISIT', externalServiceUrl: 'https://spa.gov.iq/regpage/regipage.aspx', requiredDocuments: [doc('البطاقة الوطنية أو هوية الأحوال المدنية لرب الأسرة وأفرادها مع صورة حديثة لرب الأسرة فقط'), doc('تأييد سكن'), doc('ما يؤيد الشمول بقانون ذوي الإعاقة', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'ذوو الإعاقة والاحتياجات الخاصة' }), doc('شهادة وفاة وصورة قيد', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'الأرملة أو اليتيم بحسب الحالة' }), doc('قرار بالطلاق وصورة قيد وقرار حضانة', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'المطلقة بحسب الحالة' })], requiredInformation: ['بيانات رب الأسرة', 'بيانات الأسرة'], eligibilityConditions: ['التعهد بصحة المعلومات', 'ألا يتقاضى مقدم الطلب راتباً من الدولة وألا يكون له أو لأسرته مورد دخل خاص وفق الشروط المنشورة', 'الأسبقية في التقديم لا تعني استحقاق الإعانة قبل التدقيق والبحث الاجتماعي'], feeDetails: [{ rule: 'الخدمة', amount: 0, currency: 'IQD', status: 'لا توجد رسوم وفق المصدر' }], processingTime: 'الانتظار لحين زيارة الباحث الاجتماعي', processingTimeStatus: 'OFFICIAL', citizenSteps: ['الانتقال إلى الاستمارة الرسمية', 'الموافقة على التعهد', 'إدخال بيانات رب الأسرة والأسرة', 'طباعة الطلب والاحتفاظ به', 'انتظار زيارة الباحث الاجتماعي', 'تحديد الحالة بعد المقاطعة والتدقيق والبحث الاجتماعي'], physicalPresenceRequired: false, inspectionRequired: true, inspectionDetails: 'زيارة الباحث الاجتماعي.', serviceOutput: 'طلب تسجيل يخضع للبحث والتدقيق؛ لا يعني التسجيل قبول الإعانة.', legalBasis: [{ lawName: 'قانون الحماية الاجتماعية', lawNumber: '11', year: 2014 }], verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/50459/10038/cat', 'الاستمارة الإلكترونية للتسجيل في قاعدة بيانات الفقر')],
  },
  {
    canonicalServiceId: 'ur-university-dormitory', officialNameAr: 'تقديم طلب إلكتروني للحصول على سكن الطلاب في الأقسام الداخلية للجامعات العراقية', shortNameAr: 'سكن الأقسام الداخلية', citizenFriendlyName: 'قدم على سكن الأقسام الداخلية', alternativeSearchNames: ['سكن طلاب', 'داخلية جامعة', 'قسم داخلي', 'دور الطلاب'],
    description: 'تقديم إلكتروني للسكن في الأقسام الداخلية للجامعات العراقية، ثم تدقيق من القسم المختص وإشعار بالقبول أو الرفض.', category: 'التعليم والتعلم', subcategory: 'التعليم العالي', beneficiaryTypes: ['Student'], responsibleMinistry: 'وزارة التعليم العالي والبحث العلمي', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_IN_PERSON', externalServiceUrl: 'https://eservice.ur.gov.iq/customer/applyService/10708', requiredDocuments: [doc('النتيجة الدراسية للمرحلة السابقة'), doc('كتاب تأييد استمرار بالدراسة'), doc('البطاقة الوطنية', { frontSideRequired: true, backSideRequired: true }), doc('بطاقة السكن', { frontSideRequired: true, backSideRequired: true }), doc('صور شخصية حديثة ملونة بخلفية بيضاء 3/4')], eligibilityConditions: ['ملء تعهد السكن', 'ملء تعهد الكفيل الضامن', 'لا يحق التقديم للطالب من المحافظة نفسها وفق الإجابة المنشورة في الصفحة'], feeDetails: [{ rule: 'رسوم السكن', amount: null, currency: 'IQD', status: 'تختلف حسب الحالة الدراسية وفق المصدر' }], processingTimeStatus: 'NOT_PUBLISHED', citizenSteps: ['تسجيل الدخول إلى بوابة أور', 'إدخال البيانات وتحميل الوثائق', 'إرسال الطلب', 'انتظار إشعار القبول أو الرفض', 'مراجعة قسم شؤون الأقسام الداخلية عند القبول مع الوثائق والتعهدات'], physicalPresenceRequired: true, physicalPresenceDetails: 'مراجعة قسم شؤون الأقسام الداخلية عند القبول.', serviceOutput: 'قرار قبول أو رفض وإكمال إجراءات السكن.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51250/16/org', 'تقديم طلب إلكتروني للحصول على سكن الطلاب في الأقسام الداخلية للجامعات العراقية')],
  },
  {
    canonicalServiceId: 'ur-medical-driving-exam-booking', officialNameAr: 'الحجز الإلكتروني للفحص الطبي الخاص بالحصول على إجازة السياقة - معززة بالدفع الإلكتروني', shortNameAr: 'فحص طبي لإجازة السياقة', citizenFriendlyName: 'احجز الفحص الطبي لإجازة السياقة', alternativeSearchNames: ['فحص طبي سياقة', 'فحص إجازة سوق', 'لجنة طبية سياقة'],
    description: 'حجز إلكتروني للفحص الطبي الخاص بإجازة السياقة، مع تدقيق وفحوصات مختبرية وبصرية وطبية ثم استلام قرار اللجنة.', category: 'الصحة والسلامة والبيئة', subcategory: 'الفحص الطبي', beneficiaryTypes: ['Citizen', 'Resident', 'Driver'], responsibleMinistry: 'وزارة الصحة العراقية', responsibleAuthority: 'دائرة العيادات الطبية الشعبية', administrativeLevel: 'FEDERAL_MINISTRY', availableInDhiQar: true, dhiQarOffice: 'اللجنة الطبية المسائية الأولى والثانية في ذي قار وفق المصدر',
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_IN_PERSON', existingServiceKey: 'driving-license', externalServiceUrl: 'https://eservice.ur.gov.iq/customer/applyService/10457', requiredDocuments: [doc('البطاقة الوطنية', { frontSideRequired: true, backSideRequired: true }), doc('بطاقة السكن', { frontSideRequired: true, backSideRequired: true })], eligibilityConditions: ['إنشاء حساب ضمن بوابة أور'], feeDetails: [{ rule: 'رسم الفحص للمواطن العراقي', amount: 40000, currency: 'IQD' }, { rule: 'رسم الحجز الخاص دون حجز إلكتروني للمواطن العراقي', amount: 100000, currency: 'IQD' }, { rule: 'رسم الفحص للأجنبي', amount: 150000, currency: 'IQD' }], processingTime: 'يوم عمل', processingTimeStatus: 'OFFICIAL', citizenSteps: ['تسجيل الدخول إلى بوابة أور', 'إدخال المعلومات ورفع المستمسكات', 'حفظ وإرسال الطلب', 'تحميل وثيقة الطلب وQR', 'تقديم الاستمارة والوثائق إلى اللجنة الطبية', 'إجراء التحاليل وفحص البصر والفحص الطبي', 'استلام قرار اللجنة'], physicalPresenceRequired: true, physicalPresenceDetails: 'إجراء الفحص واستلام قرار اللجنة حضورياً.', digitalDocumentAvailable: true, qrVerificationAvailable: true, serviceOutput: 'قرار اللجنة الطبية للفحص الخاص بإجازة السياقة.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51039/12/org', 'الحجز الإلكتروني للفحص الطبي الخاص بالحصول على إجازة السياقة')],
  },
  {
    canonicalServiceId: 'ur-private-benefit-water-well', officialNameAr: 'تقديم طلب إلكتروني لحفر الآبار المائية لأغراض المنفعة الخاصة', shortNameAr: 'حفر بئر مائي', citizenFriendlyName: 'قدم طلب حفر بئر للمنفعة الخاصة', alternativeSearchNames: ['حفر بئر', 'بئر ماء', 'إجازة بئر', 'مياه جوفية'],
    description: 'خدمة إلكترونية لحفر آبار مائية للمنفعة الخاصة في محافظات العراق عدا إقليم كردستان، وفق تدقيق الجهة المختصة.', category: 'الزراعة والري', subcategory: 'المياه الجوفية', beneficiaryTypes: ['Citizen', 'Farmer', 'Land Owner', 'Business Owner'], responsibleMinistry: 'وزارة الموارد المائية', responsibleAuthority: 'الهيأة العامة للمياه الجوفية', administrativeLevel: 'FEDERAL_MINISTRY', availableInDhiQar: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_IN_PERSON', externalServiceUrl: 'https://eservice.ur.gov.iq/customer/applyService/136', requiredDocuments: [doc('هوية الأحوال المدنية وشهادة الجنسية أو البطاقة الوطنية'), doc('بطاقة السكن'), doc('البطاقة التموينية'), doc('سند ملكية الأرض أو عقد زراعي ساري المفعول'), doc('مرتسم شفاف أو إحداثيات الأرض'), doc('سلامة الموقف القانوني لملكية الأرض'), doc('تعهد خطي بحماية الفرق والآليات'), doc('كتاب من مديرية الموارد المائية في المحافظة يبين عدم توفر حصة مائية أو عدم الممانعة من الحفر')], eligibilityConditions: ['إنشاء حساب ضمن بوابة أور'], feeDetails: [{ rule: 'رسم طابع', amount: 6000, currency: 'IQD' }, { rule: 'كلفة الحفر والمستلزمات', amount: null, currency: 'IQD', status: 'تحددها اللجنة المختصة حسب الحالة وعمق البئر ونوعية التربة' }], processingTime: '2–15 يوم حسب طبيعة التربة وفق النص المنشور', processingTimeStatus: 'OFFICIAL', citizenSteps: ['تسجيل الدخول إلى بوابة أور', 'إدخال البيانات وتحميل الوثائق', 'حفظ وإرسال الطلب', 'تحميل وثيقة الطلب وQR', 'متابعة الرسائل النصية الخاصة بمراحل الطلب وحالته'], physicalPresenceRequired: true, inspectionRequired: true, inspectionDetails: 'تتطلب المعاملة تدقيقاً فنياً وإجراءات من الجهة المختصة وفق المستمسكات والتعليمات المنشورة.', digitalDocumentAvailable: true, qrVerificationAvailable: true, serviceOutput: 'طلب حفر بئر يخضع للإجراءات الفنية واللجان المختصة.', legalBasis: [{ regulation: 'تعليمات التعديل الأول لتعليمات حفر الآبار المائية رقم 1 لسنة 2011', officialSource: 'https://www.moj.gov.iq/uploaded/4377.pdf' }], verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/40413/10043/org', 'تقديم طلب إلكتروني لحفر الآبار المائية لأغراض المنفعة الخاصة')],
  },
  {
    canonicalServiceId: 'ur-company-registration-one-stop', officialNameAr: 'التقديم الإلكتروني لتسجيل الشركات في نظام النافذة الواحدة', shortNameAr: 'تسجيل الشركات', citizenFriendlyName: 'أسس شركة عبر نظام النافذة الواحدة', alternativeSearchNames: ['تأسيس شركة', 'سجل شركة', 'تسجيل شركة', 'نافذة واحدة شركات'],
    description: 'نظام إلكتروني لإدارة تسجيل الشركات، وحجز الاسم التجاري، والحصول على المعرّف الضريبي ورقم الضمان الاجتماعي، مع رفع المستندات ودفع الرسوم ومتابعة الملف.', category: 'الأعمال والعاملون لحسابهم الخاص', subcategory: 'تسجيل الشركات', beneficiaryTypes: ['Company', 'Investor', 'Legal Representative', 'Business Owner'], responsibleMinistry: 'وزارة التجارة العراقية', responsibleAuthority: 'دائرة تسجيل الشركات', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE_THEN_IN_PERSON', externalServiceUrl: 'https://business.mot.gov.iq/', requiredDocuments: [doc('تعهد بالالتزام بالأنظمة موقع من مقدم الطلب'), doc('هوية وطنية أو هوية أحوال مدنية وشهادة جنسية للمؤسسين العراقيين', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'للمؤسسين العراقيين' }), doc('جواز سفر مع ترجمته', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'للمؤسسين الأجانب' }), doc('بطاقة السكن للمؤسسين العراقيين'), doc('بطاقة التموينية', { requiredOrOptional: 'OPTIONAL', appliesWhen: 'للمساهمين الحاصلين عليها' }), doc('الموافقات القطاعية', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'إن وجدت' })], feeDetails: [{ rule: 'أجور تسجيل باقي أنواع الشركات', amount: 20000, currency: 'IQD' }, { rule: 'نشر قرار التأسيس', amount: 25000, currency: 'IQD' }, { rule: 'توثيق معلومات مؤسسي الشركات الأخرى', amount: 5000, currency: 'IQD' }, { rule: 'تدقيق عقد التأسيس', amount: 5000, currency: 'IQD' }, { rule: 'طلب تأييد', amount: 10000, currency: 'IQD' }, { rule: 'طلب حفظ وتأييد عقود التأسيس', amount: 5000, currency: 'IQD' }, { rule: 'أجور منح استمارة المراجعين', amount: 3000, currency: 'IQD' }, { rule: 'رسم طابع الحملة الوطنية لبناء المدارس ورياض الأطفال', amount: 1000, currency: 'IQD' }, { rule: 'الرسم الإجمالي المنشور', amount: 74650, currency: 'IQD', status: 'توجد أيضاً قواعد رسم طابع مرتبطة بقيمة رأس المال وفق المصدر' }], processingTimeStatus: 'NOT_PUBLISHED', citizenSteps: ['إنشاء حساب في النافذة الواحدة', 'ملء الاستمارة ورفع المستندات', 'تحويل المعاملة إلى دائرة تسجيل الشركات', 'استلام إشعار الرسوم لكل جهة', 'الدفع الإلكتروني', 'متابعة الملف إلى حين الإشعار بتسلم الشهادات', 'تقديم أصول بعض المستندات عند التسلم'], physicalPresenceRequired: true, physicalPresenceDetails: 'تسلم شهادة التسجيل يتطلب تقديم أصول بعض المستندات وفق المصدر.', digitalDocumentAvailable: true, serviceOutput: 'إجراءات تأسيس وتسجيل شركة وشهادات تصدرها الجهة المختصة.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/20111/10041/cat', 'التقديم الإلكتروني لتسجيل الشركات في نظام النافذة الواحدة')],
  },
  {
    canonicalServiceId: 'ur-human-rights-violation-report', officialNameAr: 'تقديم طلب إلكتروني للإبلاغ عن حدوث انتهاك حقوق الإنسان', shortNameAr: 'الإبلاغ عن انتهاك', citizenFriendlyName: 'أبلغ عن انتهاك حقوق الإنسان', alternativeSearchNames: ['انتهاك حقوق الإنسان', 'بلاغ حقوق', 'شكوى انتهاك'], description: 'خدمة إلكترونية لرصد وتوثيق انتهاكات حقوق الإنسان التي تمس الفئات المشمولة برعاية الوزارة، وإحالتها للدعم والمتابعة مع الجهات المختصة.', category: 'العدل والقانون والتظلمات', subcategory: 'حقوق الإنسان', beneficiaryTypes: ['Citizen', 'Resident', 'Legal Representative'], responsibleMinistry: 'وزارة الهجرة والمهجرين', responsibleDepartment: 'الدائرة القانونية', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE', externalServiceUrl: 'https://eservice.ur.gov.iq/customer/applyService/21378', requiredDocuments: [doc('صور أو وثائق توثق الانتهاك', { requiredOrOptional: 'OPTIONAL', notes: 'تتيح الصفحة تحميل مرفقين للطلب' })], eligibilityConditions: ['إنشاء حساب ضمن بوابة أور'], feeDetails: [{ rule: 'الخدمة', amount: 0, currency: 'IQD', status: 'لا توجد رسوم وفق المصدر' }], processingTime: '25 يوم عمل', processingTimeStatus: 'OFFICIAL', citizenSteps: ['تسجيل الدخول إلى بوابة أور', 'إدخال المعلومات ورفع المرفقات', 'حفظ وإرسال الطلب', 'تحميل وثيقة الطلب وQR', 'استلام إشعار عند اكتمال المعالجة'], digitalDocumentAvailable: true, qrVerificationAvailable: true, serviceOutput: 'بلاغ يحال إلى الدائرة القانونية والجهات المختصة.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51671/all/all', 'تقديم طلب إلكتروني للإبلاغ عن حدوث انتهاك حقوق الانسان')],
  },
  {
    canonicalServiceId: 'ur-sports-facility-booking', officialNameAr: 'التقديم الإلكتروني لحجز المنشآت الرياضية في بغداد والمحافظات', shortNameAr: 'حجز منشأة رياضية', citizenFriendlyName: 'احجز منشأة شبابية أو رياضية', alternativeSearchNames: ['حجز ملعب', 'حجز قاعة رياضية', 'منشأة رياضية', 'بيت شباب'],
    description: 'تقديم إلكتروني لحجز منشأة شبابية أو رياضية تابعة لوزارة الشباب والرياضة للأنشطة الشبابية والرياضية والاجتماعية.', category: 'الشباب والرياضة والثقافة', subcategory: 'الشباب والرياضة', beneficiaryTypes: ['Citizen', 'Company', 'Other'], responsibleMinistry: 'وزارة الشباب والرياضة', responsibleDepartment: 'دائرة شؤون الأقاليم والمحافظات', administrativeLevel: 'FEDERAL_MINISTRY', availableNationwide: true,
    serviceType: 'EXTERNAL_DIGITAL_SERVICE', applicationChannel: 'ONLINE', externalServiceUrl: 'https://eservice.ur.gov.iq/customer/applyService/21220', requiredDocuments: [doc('البطاقة الوطنية', { frontSideRequired: true, backSideRequired: true }), doc('بطاقة السكن', { frontSideRequired: true, backSideRequired: true }), doc('كتاب الموافقة', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'نوع الحجز موافقة مجانية' }), doc('كتاب رسمي', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'إن وجد' }), doc('قائمة بأسماء الوفود', { requiredOrOptional: 'CONDITIONAL', appliesWhen: 'حجز بيت الشباب' })], eligibilityConditions: ['المحافظة على المنشآت وعدم العبث بالموجودات', 'استخدام المنشأة للأغراض المصرح بها'], feeDetails: [{ rule: 'الخدمة', amount: 0, currency: 'IQD', status: 'لا توجد رسوم وفق المصدر' }], processingTime: '2 ساعة عمل', processingTimeStatus: 'OFFICIAL', citizenSteps: ['تسجيل الدخول إلى بوابة أور', 'إدخال البيانات وتحميل الوثائق', 'إرسال الطلب وتحميل وثيقة الطلب وQR', 'استلام إشعار بموعد الحجز عند الموافقة'], digitalDocumentAvailable: true, qrVerificationAvailable: true, serviceOutput: 'إشعار أو موعد حجز منشأة.', verificationStatus: 'VERIFIED_UR_PORTAL', lastVerifiedDate: verifiedOn, sourceDate: verifiedOn, publicationStatus: 'APPROVED', sources: [urSource('https://ur.gov.iq/index/show-eservice/51650/10048/cat', 'التقديم الإلكتروني لحجز المنشآت الرياضية في بغداد والمحافظات')],
  },
]

export function seedVerifiedGovernmentServices() {
  for (const record of verifiedGovernmentServiceSeed) {
    const exists = db.prepare('SELECT id FROM government_service_directory WHERE canonical_service_id = ?').get(record.canonicalServiceId)
    if (!exists) upsertGovernmentService(record, 'OFFICIAL_SOURCE_IMPORT')
  }
}
