import { chromium } from 'playwright'
const base = 'http://localhost:8787'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const page = await browser.newPage({ viewport: { width: 1360, height: 900 } })
const errors = []
page.on('pageerror', e => errors.push(`pageerror: ${e.message}`))
await page.goto(`${base}/staff/login?next=%2Fsuper-admin`, { waitUntil: 'networkidle' })
await page.screenshot({ path: 'qa-screens/staff-login.png' })
await page.fill('input[autocomplete="username"]', 'operations')
await page.fill('input[autocomplete="current-password"]', '2468')
await page.click('button[type=submit]')
await page.waitForTimeout(1500)
await page.screenshot({ path: 'qa-screens/staff-login-password-change.png' })
console.log('after login:', page.url(), (await page.textContent('.staff-login-card strong')))
await page.fill('input[autocomplete="new-password"] >> nth=0', 'Ops-Strong-Pass-2026!')
await page.fill('input[autocomplete="new-password"] >> nth=1', 'Ops-Strong-Pass-2026!')
await page.click('button[type=submit]')
await page.waitForTimeout(2500)
console.log('after change:', page.url())
await page.screenshot({ path: 'qa-screens/after-password-change.png' })
await page.request.post(`${base}/api/auth/logout`)
await page.goto(`${base}/staff/login`, { waitUntil: 'networkidle' })
await page.fill('input[autocomplete="username"]', 'employee')
await page.fill('input[autocomplete="current-password"]', 'Strong-Pass-2026!')
await page.click('button[type=submit]')
await page.waitForTimeout(2500)
console.log('employee ->', page.url())
await page.screenshot({ path: 'qa-screens/employee-dashboard.png', fullPage: false })
await page.goto(`${base}/staff/security`, { waitUntil: 'networkidle' })
await page.screenshot({ path: 'qa-screens/security-page.png', fullPage: true })
await browser.close()
console.log(errors.length ? errors.join('\n') : 'no page errors')
