/** Arabic labels for every audit action the server records (fallback: humanised code). */
export const auditActionLabels: Record<string, string> = {
  APPLICATION_APPROVED_DOCUMENT_ISSUED: 'موافقة وإصدار وثيقة',
  APPLICATION_CREATED: 'تقديم معاملة',
  APPLICATION_REJECTED: 'رفض معاملة',
  APPLICATION_VIEW: 'عرض معاملة',
  CITIZEN_LOCATION_UPDATED: 'تحديث موقع المواطن',
  CITIZEN_PROFILE_PHOTO_VIEWED: 'عرض صورة الملف',
  CREATED: 'إنشاء',
  UPDATED: 'تحديث',
  DATABASE_BACKUP_CREATED: 'نسخة احتياطية لقاعدة البيانات',
  DEPARTMENT_CAMERA_CONFIGURED: 'إعداد كاميرا الدائرة',
  DEPARTMENT_DASHBOARD_VIEWED: 'فتح لوحة الدائرة',
  DOCUMENT_REQUESTED: 'طلب مستند',
  DOCUMENT_VERIFIED: 'تدقيق مستند',
  FEEDBACK_STATUS_UPDATED: 'تحديث شكوى / مقترح',
  IDENTITY_MEDIA_RETAINED_AFTER_DECISION: 'الاحتفاظ بوسائط الهوية بعد القرار',
  IDENTITY_MEDIA_SUBMITTED: 'إرسال وسائط الهوية',
  IDENTITY_MEDIA_VIEWED: 'عرض وسيط هوية',
  IDENTITY_REVIEW_DECIDED: 'قرار مراجعة هوية',
  IDENTITY_REVIEW_QUEUE_VIEWED: 'فتح قائمة مراجعة الهوية',
  IDENTITY_REVIEW_REQUESTED: 'طلب مراجعة هوية',
  ISSUED_DOCUMENT_OPENED: 'فتح وثيقة صادرة',
  ISSUED_DOCUMENT_ORIGINAL_OPENED: 'فتح أصل وثيقة صادرة',
  ISSUED_DOCUMENT_VERIFIED: 'التحقق من وثيقة صادرة',
  LOCAL_TEST_DATA_RESET: 'إعادة تعيين بيانات الاختبار',
  MISSING_DOCUMENT_UPLOADED: 'رفع مستند ناقص',
  NOTIFICATIONS_MARKED_READ: 'تعليم الإشعارات كمقروءة',
  PAYMENT_REQUIRED: 'طلب دفع',
  PHONE_OTP_REQUESTED: 'طلب رمز تحقق',
  PHONE_OTP_VERIFIED: 'تأكيد رقم الهاتف',
  PLATFORM_SERVICE_UPDATED: 'تحديث إعدادات خدمة',
  PROFILE_VIEW: 'عرض الملف الشخصي',
  SERVICE_DOCUMENT_VIEWED: 'عرض مستمسك طلب خدمة',
  SERVICE_DOCUMENT_VERIFIED: 'قبول مستمسك',
  SERVICE_DOCUMENT_REJECTED: 'رفض مستمسك',
  SERVICE_REQUEST_CREATED: 'تقديم طلب خدمة',
  APPOINTMENT_REQUESTED: 'طلب موعد',
  SERVICE_REQUEST_DECIDED: 'قرار على طلب خدمة',
  SERVICE_REQUEST_APPROVED_DOCUMENT_ISSUED: 'موافقة على طلب خدمة وإصدار وثيقة',
  SERVICE_REQUEST_APPROVED: 'موافقة على طلب خدمة',
  SERVICE_REQUEST_REJECTED: 'رفض طلب خدمة',
  SERVICE_REQUEST_ACTION_REQUIRED: 'إعادة طلب خدمة للمواطن (نواقص)',
  SERVICE_REQUEST_UNDER_REVIEW: 'بدء تدقيق طلب خدمة',
  SERVICE_REQUEST_DOCUMENT_UPLOADED: 'رفع مستمسك لطلب خدمة',
  SESSION_ENDED: 'تسجيل خروج',
  SET_GOVERNMENT_SERVICE_PUBLICATION: 'نشر / إخفاء خدمة وطنية',
  STAFF_ACCOUNTS_BOOTSTRAPPED: 'تهيئة حسابات الموظفين',
  STAFF_ACCOUNT_CREATED: 'إنشاء حساب موظف',
  STAFF_ACCOUNT_LOCKED: 'قفل حساب موظف',
  STAFF_ACCOUNT_UPDATED: 'تحديث حساب موظف',
  STAFF_LOGIN_FAILED: 'محاولة دخول فاشلة',
  STAFF_MFA_DISABLED: 'تعطيل التحقق الثنائي',
  STAFF_MFA_ENABLED: 'تفعيل التحقق الثنائي',
  STAFF_MFA_FAILED: 'فشل رمز التحقق الثنائي',
  STAFF_MFA_RESET: 'إعادة تعيين التحقق الثنائي',
  STAFF_PASSWORD_CHANGED: 'تغيير كلمة المرور',
  STAFF_PASSWORD_RESET: 'إعادة تعيين كلمة المرور',
  STAFF_SESSIONS_REVOKED: 'إنهاء الجلسات',
  STAFF_SESSIONS_REVOKED_BY_ADMIN: 'إنهاء الجلسات بواسطة المدير',
  STAFF_SESSION_CREATED: 'تسجيل دخول',
  WORKFORCE_SNAPSHOT_RECORDED: 'تسجيل بيانات الملاك',
}

export const auditActionLabel = (action: string) =>
  auditActionLabels[action] || action.toLowerCase().replaceAll('_', ' ')
